### ISSUE TITLE
timeline has no sane default

### ISSUE THREAD

**Issue by srkunze** [zware/codespeed#1]
Before complaining: great work! +1

Alright, back to business: https://speed.python.org/timeline/ doesn't show anything useful for the first time I visited it.

**Comment by zware** [comment]
Thanks :)

As far as the issue you raised, I believe that will be mitigated by having more than one result available, we'll see when that's the case. I'll leave this open until then, and if it's still an issue afterward it will need to be reported upstream at tobami/codespeed.

**Comment by tobami** [comment]
@zware AFAIK you are using `master` (for Python 3 compat). If that is the case, timeline was broken after upgrading jqPlot. If you upgrade to current master it should work again.

I also want to smooth some other Python 3 rough edges in the next few weeks and then release a new stable version.

**Comment by zware** [comment]
@tobami Thanks, timeline appears to be working now after an update.  As far as setting a default view, I'm not sure how to do that.

**Comment by tobami** [comment]
You mean you would like to have the url root (`speed.python.org`) pointing to changes or timeline view, for example?

(In any case the issue can probably be closed)

**Comment by zware** [comment]
Actually, what I meant was to show a default (selection of) graph(s) when clicking the timeline tab, which I assumed was what @srkunze was going for, but I may have been mistaken on that.

Anyway, I agree that this is fixed enough to close.
