### ISSUE TITLE
sane defaults for comparison

### ISSUE THREAD

**Issue by srkunze** [zware/codespeed#2]
As with #1, the diagram isn't overly useful right now with no normalization present. At least I don't see anything except one big bar. :D

**Comment by JimJJewett** [comment]
hexiom2 is way out of scale; it works on its own, and "everything else" works sort of ... still too squished side-to-side for me to be sure.

**Comment by zware** [comment]
hexiom2 and telco are kind of outliers. hexiom2 takes a long time on both versions, telco takes a long time on Python 2. Stefan Krah has already opened an issue for fixing telco, I'm not sure what we might do about hexiom2. In the meantime, deselecting both of them makes the rest a bit more comparable.

**Comment by zware** [comment]
Looking again, telco isn't nearly the outlier I'd thought it was (and I'm not sure where I picked up that impression).

I have gone through and removed hexiom2 and all of the python2-only benchmarks from the default view on the comparison page, which also mitigates #3.

**Comment by zware** [comment]
I think this is covered enough with the change in which benchmarks are shown by default.
